# Generated by Django 4.2.1 on 2023-05-08 13:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('name_on_japan', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=500)),
                ('slug', models.SlugField(blank=True, default='djangodbmodelsfieldscharfield')),
                ('release_type', models.CharField(choices=[('film', 'Film'), ('tv_serial', 'TV Serial'), ('ova', 'OVA')], max_length=64)),
                ('release_date', models.DateTimeField(default=datetime.datetime(2023, 5, 8, 13, 58, 28, 54709, tzinfo=datetime.timezone.utc))),
                ('add_date', models.DateTimeField(default=datetime.datetime(2023, 5, 8, 13, 58, 28, 54729, tzinfo=datetime.timezone.utc))),
                ('status', models.CharField(choices=[('complete', 'Complete'), ('on_going', 'On going')], max_length=64)),
                ('views', models.PositiveIntegerField(default=0)),
                ('duration', models.PositiveIntegerField(default=24, verbose_name='Episode duration in minutes')),
                ('poster', models.ImageField(upload_to='posters')),
                ('finish_episode_count', models.PositiveIntegerField(default=12, verbose_name='How many episodes are planned')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('number', models.PositiveIntegerField(verbose_name='Which episode is in order')),
                ('video', models.FileField(upload_to='episodes/None/')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='anime.anime')),
            ],
        ),
        migrations.CreateModel(
            name='Gengre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('slug', models.SlugField(blank=True, default='djangodbmodelsfieldscharfield')),
            ],
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField()),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime.anime')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('create_date', models.DateTimeField(default=datetime.datetime(2023, 5, 8, 13, 58, 28, 56906, tzinfo=datetime.timezone.utc))),
                ('anime', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='anime.anime')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('episode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='anime.episode')),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime.anime')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='anime',
            name='genre',
            field=models.ManyToManyField(related_name='genres', to='anime.gengre'),
        ),
        migrations.AddField(
            model_name='anime',
            name='studio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime.studio'),
        ),
    ]
