# Generated by Django 4.2.1 on 2023-05-08 14:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 8, 14, 0, 52, 106843, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='anime',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 8, 14, 0, 52, 106822, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='review',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 8, 14, 0, 52, 108952, tzinfo=datetime.timezone.utc)),
        ),
    ]
