# Generated by Django 4.2.1 on 2023-05-10 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0003_alter_anime_add_date_alter_anime_release_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='anime',
            name='release_type',
            field=models.CharField(choices=[('Film', 'Film'), ('TV Serial', 'TV Serial'), ('OVA', 'OVA')], max_length=64),
        ),
        migrations.AlterField(
            model_name='anime',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='status',
            field=models.CharField(choices=[('Complete', 'Complete'), ('On going', 'On going')], max_length=64),
        ),
        migrations.AlterField(
            model_name='episode',
            name='video',
            field=models.FileField(upload_to='episodes/'),
        ),
        migrations.AlterField(
            model_name='gengre',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='anime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='anime.anime'),
        ),
        migrations.AlterField(
            model_name='review',
            name='episode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='anime.episode'),
        ),
    ]
