# Generated by Django 4.2.1 on 2023-05-10 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0005_anime_image_for_featured'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anime',
            old_name='image_for_featured',
            new_name='image_featured',
        ),
    ]
