# Generated by Django 4.2.1 on 2023-05-10 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0006_rename_image_for_featured_anime_image_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='rating',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
