# Generated by Django 4.2.1 on 2023-05-10 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0009_anime_vote_alter_vote_anime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='vote',
        ),
        migrations.AddField(
            model_name='anime',
            name='vote',
            field=models.ManyToManyField(null=True, related_name='votes', to='anime.vote'),
        ),
    ]
